version: 2.1

setup: true

orbs:
  path-filtering: circleci/path-filtering@0.1.1

workflows:
  always-run:
    jobs:
      - path-filtering/filter:
          name: check-updated-files

          mapping: |
            test1/.* run-test-1 true
            test2/.* run-test-2 true
          base-revision: main
          config-path: .circleci/testing.yml
