version: 2.1

parameters:
  run-test-1:
    type: boolean
    default: false
  run-test-2:
    type: boolean
    default: false

workflows:
  test-1:
    when: << pipeline.parameters.run-test-1 >>
    jobs:
      name: test1
      command: "go test ./test1"
  test-2:
    when: << pipeline.parameters.run-test-2 >>
    jobs:
      name: test2
      command: "go test ./test2"
